baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "terminal"

paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about"
    weight = 2
  [[menu.main]]
    identifier = "posts"
    name = "Noticias"
    title = "Posts"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    identifier = "main"
    name = "Pagina Principal"
    title = "Pagina Principal"
    url = "/main"
    weight = 1