baseURL = 'https://example.org/'
languageCode = 'es'
title = 'Aston Martin Updates'
theme = "terminal"

paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true
  css = ["css/estilos.css"]

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about"
    weight = 5
  [[menu.main]]
    identifier = "posts"
    name = "Noticias"
    title = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "main"
    name = "Pagina Principal"
    title = "Pagina Principal"
    url = "/main"
    weight = 1
  [[menu.main]]
    identifier = "formula1"
    name = "Formula 1"
    title = "Formula 1"
    url = "/formula1/"
    weight = 3
  [[menu.main]]
    identifier = "wec"
    name = "WEC"
    title = "WEC"
    url = "/wec/"
    weight = 4